### ISSUE TITLE
Setup isn't explained well.

### ISSUE THREAD

**Issue by searriez** [Cerulity64X/mh71_clickbot#2]
You say "Navigate to the folder the executable is contained in and save it as macro.json". Do I save the exe as macro.json or the macro as macro.json?

You say "In the assets folder"... what assets folder?

I assumed like 3 things here, and it's not working. Do you mind explaining how to do everything in greater detail?

**Comment by Cerulity32K** [comment]
I definitely could've made clearer instructions. I will update the instructions and will possibly make a video explanation. Thank you for telling me about this.
